s--
- hosts: all
  tasks:
    - name: Install openscap
      yum: 
        name: '{{ item }}'
        state: latest
      with_items:
        - openscap-scanner
        - scap-security-guide

    - name: remediate openscap RHEL
      shell: "oscap xccdf eval --remediate --profile '{{ profile }}' --results /root/scan-xccdf-results.xml /usr/share/xml/scap/ssg/content/ssg-rhel7-ds.xml"
      ignore_errors: yes
      register: command_result
      failed_when: "'FAILED' in command_result.stderr"
      when: ansible_distribution == "RedHat"

    - name: remediate openscap  CENTOS
      shell: "oscap xccdf eval --remediate --profile '{{ profile }}' --results /root/scan-xccdf-results.xml /usr/share/xml/scap/ssg/content/ssg-centos7-ds.xml"
      ignore_errors: yes
      register: command_result
      failed_when: "'FAILED' in command_result.stderr"
      when: ansible_distribution == "CentOS"

    - name: Prepare report
      shell: "oscap xccdf generate report /root/scan-xccdf-results.xml > /root/index.html"
