---
- hosts: all
  become: true
  tasks:
    - name: Install openscap
      yum: 
        name: '{{ item }}'
        state: latest
      with_items:
        - openscap-scanner
        - scap-security-guide

    - name: openscap Scan
      shell: 'oscap xccdf eval --profile xccdf_org.ssgproject.content_profile_rht-ccp --results /root/scan-xccdf-results.xml --report /root/scan-xccdf-report.html /usr/share/xml/scap/ssg/content/ssg-rhel7-ds.xml'
      ignore_errors: yes
      register: command_result
      failed_when: "'FAILED' in command_result.stderr"

    - name: remediate openscap
      shell: 'oscap xccdf eval --remediate --profile xccdf_org.ssgproject.content_profile_rht-ccp --results /root/scan-xccdf-results.xml /usr/share/xml/scap/ssg/content/ssg-rhel7-ds.xml'
      ignore_errors: yes
      register: command_result
      failed_when: "'FAILED' in command_result.stderr"
