---
- hosts: all
  become: true
  tasks:
    - name: Install openscap
      yum: 
        name: '{{ item }}'
        state: latest
      with_items:
        - openscap-scanner
        - scap-security-guide
        - httpd
  
    - service: 
        name: httpd
        state: started
    - name: openscap Scan
      shell: "oscap xccdf eval --profile '{{ profile }}'--results /root/scan-xccdf-results.xml --report /var/www/html/index.html /usr/share/xml/scap/ssg/content/ssg-rhel7-ds.xml"
      ignore_errors: yes
      register: command_result
      failed_when: "'FAILED' in command_result.stderr"

    - name: remediate openscap
      shell: "oscap xccdf eval --remediate --profile '{{ profile }}' --results /root/scan-xccdf-results.xml /usr/share/xml/scap/ssg/content/ssg-rhel7-ds.xml"
      ignore_errors: yes
      register: command_result
      failed_when: "'FAILED' in command_result.stderr"
     
    - name: Prepare report
      file: 
        path: /var/www/html/index.html
        mode: 0644
        owner: apache
        group: apache
